namespace BlackHole.Identifiers
{
    internal class AutoGeneratedProperty
    {
        internal string PropertyName { get; set; } = string.Empty;
        internal bool Autogenerated { get; set; }
        internal object? Generator { get; set; }
    }

    internal class DefaultValueProperty
    {
        internal string PropertyName { get; set; } = string.Empty;
        internal object? ValueIfNull { get; set; }
    }
}
