namespace BlackHole.Identifiers
{
    /// <summary>
    /// 
    /// </summary>
    public class AutoGeneratedProperty
    {
        internal string PropertyName { get; set; } = string.Empty;
        internal bool Autogenerated { get; set; }
        internal object? Generator { get; set; }
    }
}
