
using System.Linq.Expressions;

namespace BlackHole.Entities
{
    /// <summary>
    /// 
    /// </summary>
    public class PKOptionsBuilder<T>
    {
        internal PKOptionsBuilder()
        {

        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="tKey"></typeparam>
        /// <param name="primaryKey"></param>
        public PKSettings<T> SetPrimaryKey<tKey>(Expression<Func<T,tKey>> primaryKey) where tKey : IComparable<tKey>
        {
            PKSettings<T> settings = new(false);
            if (primaryKey is MemberExpression pkMember)
            {
                settings.PKSettingsList.Add(new PrimaryKeySettings<tKey> { PropertyName = pkMember.Member.Name });
            }
            return settings;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="tKey"></typeparam>
        /// <param name="primaryKey"></param>
        /// <param name="valueGenerator"></param>
        public PKSettings<T> SetPrimaryKey<tKey>(Expression<Func<T, tKey>> primaryKey, IBHValueGenerator<tKey> valueGenerator) where tKey: IComparable<tKey> 
        {
            PKSettings<T> settings = new (false);
            if (primaryKey is MemberExpression pkMember)
            {
                settings.PKSettingsList.Add(new PrimaryKeySettings<tKey> { PropertyName = pkMember.Member.Name, Autogenerated = true, Generator = valueGenerator });
            }
            return settings;
        }

        public PKSettings<T> NoPrimaryKey()
        {
            return new PKSettings<T>(true);
        }
    }

    public class PKSettings<T>
    {
        internal List<PrimaryKeySettings> PKSettingsList { get; set; } = new List<PrimaryKeySettings>();
        internal bool LockedPK { get; set; }
        internal PKSettings(bool lockedPK)
        {
            LockedPK = lockedPK;
        }
    }

    public static class PKExtensions
    {
        public static PKSettings<T> CompositeKey<T, tKey>(this PKSettings<T> settings, Expression<Func<T, tKey>> primaryKey) where tKey : IComparable<tKey>
        {
            if (!settings.LockedPK)
            {
                if (primaryKey is MemberExpression pkMember)
                {
                    settings.PKSettingsList.Add(new PrimaryKeySettings<tKey> { PropertyName = pkMember.Member.Name });
                }
            }
            return settings;
        }

        public static PKSettings<T> CompositeKey<T, tKey>(this PKSettings<T> settings, Expression<Func<T, tKey>> primaryKey, IBHValueGenerator<tKey> valueGenerator)
            where tKey : IComparable<tKey>
        {
            if (!settings.LockedPK)
            {
                if (primaryKey is MemberExpression pkMember)
                {
                    settings.PKSettingsList.Add(new PrimaryKeySettings<tKey> { PropertyName = pkMember.Member.Name, Autogenerated = true, Generator = valueGenerator });
                }
            }
            return settings;
        }
    }
}
