
namespace BlackHole.Entities
{
    internal abstract class PrimaryKeySettings
    {
        internal string PropertyName { get; set; } = string.Empty;
        internal bool Autogenerated { get; set; }
    }

    internal class PrimaryKeySettings<T>: PrimaryKeySettings where T : IComparable<T>
    {
        internal IBHValueGenerator<T>? Generator { get; set; }
    }
}
