
namespace BlackHole.Entities
{
    internal class PrimaryKeySettings
    {
        internal string PropertyName { get; set; } = string.Empty;
        internal bool Autogenerated { get; set; }
        internal object? Generator { get; set; }
    }
}
